// <auto-generated />
namespace NijieDownloader.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _1031 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1031));
        
        string IMigrationMetadata.Id
        {
            get { return "201404021353243_1.0.3.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
